name: Move files to root

on: [push]

jobs:
  move_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Move files from subdirectories to root
      run: |
        find . -type f -path "./part*" -exec mv {} . \;
        find . -type d -name "part*" -exec rm -r {} +

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Move files to root directory"
        git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git main
